<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLx756ry\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLx756ry/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLx756ry.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLx756ry\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLx756ry\appDevDebugProjectContainer([
    'container.build_hash' => 'Lx756ry',
    'container.build_id' => 'fe68d11d',
    'container.build_time' => 1569336475,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLx756ry');
